name: Build, test and linting

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Install project dependencies
        run: poetry install
      - name: Lint with flake8
        run: |
          poetry run pflake8 sclibrary
      - name: Run tests
        run: |
          poetry run pytest
      - name: Generate coverage report
        run: |
          poetry run coverage run -m pytest && poetry run coverage report -m
          coverage xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: irtazahashmi/sc-graph-library
          file: coverage.xml
          fail_ci_if_error: false
